# Generated by Django 5.0.7 on 2024-07-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
