# Generated by Django 5.0.7 on 2024-07-24 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_user_password2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='mail',
        ),
    ]
