# Generated by Django 5.0.7 on 2024-07-24 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_rename_mail_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='mail',
        ),
    ]
