# Generated by Django 5.0.7 on 2024-07-24 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_rename_mail_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password2',
        ),
    ]
