# Generated by Django 5.0.7 on 2024-07-29 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='is_admin',
        ),
    ]
