# Generated by Django 5.0.7 on 2024-07-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_board_view_count_alter_board_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
