# Generated by Django 4.2.14 on 2024-07-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(default="제목없음", max_length=50)),
                ("file", models.FileField(upload_to="examples/")),
            ],
        ),
    ]
