# Generated by Django 4.2.5 on 2023-10-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicRequests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Enter the Subject of your Academic Request",
                        max_length=100,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Enter Description of your Academic Request Here",
                        max_length=2000,
                    ),
                ),
                (
                    "request_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the request was made",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Academic Requests",
            },
        ),
        migrations.CreateModel(
            name="AdministrativeRequests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Enter the Subject of your Request", max_length=100
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Enter Description of your Administrative Request Here",
                        max_length=2000,
                    ),
                ),
                (
                    "request_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the request was made",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Administrative Requests",
            },
        ),
    ]
