# Generated by Django 4.2.5 on 2023-10-04 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inquiries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="administrativerequests",
            name="receiver",
            field=models.ForeignKey(
                help_text="Sending to...",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="administrativerequests",
            name="sender",
            field=models.ForeignKey(
                help_text="Sent By...",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_admin_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="academicrequests",
            name="receiver",
            field=models.ForeignKey(
                help_text="Sending to...",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="academicrequests",
            name="sender",
            field=models.ForeignKey(
                help_text="Sent By...",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_academic_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
