# Generated by Django 4.2.5 on 2023-10-05 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0004_alter_academicrequests_sender_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="academicreply",
            name="academic_request",
        ),
    ]
