# Generated by Django 4.2.5 on 2023-10-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0006_administrativereply_alter_academicrequests_reply_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="academicrequests",
            name="reply",
        ),
        migrations.RemoveField(
            model_name="administrativerequests",
            name="reply",
        ),
        migrations.AddField(
            model_name="academicrequests",
            name="reply",
            field=models.ManyToManyField(blank=True, to="inquiries.academicreply"),
        ),
        migrations.AddField(
            model_name="administrativerequests",
            name="reply",
            field=models.ManyToManyField(
                blank=True, to="inquiries.administrativereply"
            ),
        ),
    ]
