# Generated by Django 4.2.5 on 2023-10-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0007_remove_academicrequests_reply_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="academicreply",
            name="reply_date",
        ),
        migrations.RemoveField(
            model_name="administrativereply",
            name="reply_date",
        ),
        migrations.AlterField(
            model_name="academicrequests",
            name="reply",
            field=models.ManyToManyField(to="inquiries.academicreply"),
        ),
        migrations.AlterField(
            model_name="administrativerequests",
            name="reply",
            field=models.ManyToManyField(to="inquiries.administrativereply"),
        ),
    ]
